# Generated by Django 5.1.1 on 2024-09-29 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_empresa_cnpj_alter_freelancer_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_empresa',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='email_freelancer',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('empresa', 'Empresa')], default='freelancer', max_length=10),
        ),
    ]
